#!/bin/bash
mydir=`dirname $0`
case `uname -s` in
    CYGWIN*)
      mydir=`cygpath -m $mydir`
      ;;
esac
export PANC_HOME=$mydir/..

# pass classpath argument through to inner java call
CP=.
NON_CP=""
FIRST=1
while [ $# -gt 0 ]
do
    ARG="$1"
    case $ARG in
        -cp)
            CP=$CP:$2
            shift 2
            ;;
        *)  [[ ${ARG#-} = $ARG && $FIRST = 1 ]] && ARG="$ARG\$thread" && FIRST=0
            NON_CP="$NON_CP $ARG"
            shift
            ;;
    esac
done
java -cp $CP:$PANC_HOME/lib/panini_rt.jar $NON_CP
